language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
sudo: false
# command to install dependencies
install:
  - pip install tox-travis tox coveralls
# command to run tests
script:
  - "tox"
after_success:
 coveralls
